# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0f2c434b9592fd13925f985f649e3e98cb9a50c2e8f3d951899fcf13714b7330db850fb3e69cd82b186f55a8819233e721f92ec072c3da8c408c48e21b7ffb4

test:
  secret_key_base: 7fbc5f3d162a8ce7432188ca8ca9133972b8edf37f5a033a95dac4669f21418b9a4a2b5e79ce33f502136e973f98604234bcfe6a24e7ecfc2ab58b5f6d81b4d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
